### ISSUE TITLE
pod 'fluid-slider' not find

### ISSUE THREAD

**Issue by markdashi** [Ramotion/fluid-slider#10]
I use Cocopods to intall  'fluid-slider'  ,but I find it didn't exists,please solute quickly.

**Comment by ober01** [comment]
Hi, minimum deployment target 10.0 https://github.com/Ramotion/fluid-slider/blob/master/fluid-slider.podspec

change first line your in podfile to `platform :ios, '10.0'` or higher

**Comment by markdashi** [comment]
Hi,this doesn't solve this problem.I guess you make a mistake in this Library.

**Comment by ober01** [comment]
![image](https://user-images.githubusercontent.com/5435782/34431221-60e3d29e-ec7e-11e7-83d4-c6b3a4c799a7.png)
it works for me

**Comment by ober01** [comment]
Could you share your podfile ?

**Comment by markdashi** [comment]
<img width="461" alt="2017-12-29 2 57 36" src="https://user-images.githubusercontent.com/13793311/34431295-e5674d5a-eca8-11e7-86c7-2eeb1fbf99ec.png">
<img width="583" alt="2017-12-29 2 56 53" src="https://user-images.githubusercontent.com/13793311/34431299-e974be50-eca8-11e7-95eb-fda6c48ed475.png">



I really didn't find this.

**Comment by ober01** [comment]
try pod update )

**Comment by markdashi** [comment]
ok ,thanks
