### ISSUE TITLE
Failed to 'import Slider' No such Module found 

### ISSUE THREAD

**Issue by NikolaosMakris11** [Ramotion/fluid-slider#12]
So I tried to embedd the fluid slider into my project and I get an Error message when I try to import the the Library. I tried to do the same thing like the Example project. I don't get it why I get this error.

<img width="262" alt="bildschirmfoto 2018-03-21 um 16 22 16" src="https://user-images.githubusercontent.com/34068648/37718989-44973342-2d24-11e8-9a11-3bc094bd0c0e.png">

And I don't think there is something wrong with my Podfile.

<img width="641" alt="bildschirmfoto 2018-03-21 um 16 21 45" src="https://user-images.githubusercontent.com/34068648/37719036-62725a4a-2d24-11e8-8873-90c874aee5d7.png">

Would be nice if someone could help.

**Comment by ober01** [comment]
you need import module ``` import fluid_slider ```
