### ISSUE TITLE
Support min iOS 9

### ISSUE THREAD

**Issue by black-lotus** [Ramotion/fluid-slider#13]
Is it possible to support with minimum requirement with iOS 9.0

**Comment by ober01** [comment]
two reasons: 
<img width="794" alt="image 2018-03-23 at 9 53 54 am" src="https://user-images.githubusercontent.com/5435782/37815536-4b1bdb34-2e80-11e8-83a3-321bbd9fc321.png">
<img width="793" alt="image 2018-03-23 at 9 54 09 am" src="https://user-images.githubusercontent.com/5435782/37815539-4ccfa654-2e80-11e8-800d-69e114da183b.png">
