### ISSUE TITLE
framework not found fluid_slider

### ISSUE THREAD

**Issue by BedirT** [Ramotion/fluid-slider#14]
```
ld: warning: directory not found for option '-F/Users/mt/Library/Developer/Xcode/DerivedData/Example-erbzcbnkrlutncedbyrdaevikjvj/Build/Products/Debug-iphonesimulator/fluid-slider'
ld: framework not found fluid_slider
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tried to clean & build no luck...

I have no idea why I am getting this error. Im not even sure if this is related to the framework or just my Mac. I tried to re-install the pods, w iOS 11.2. I am missing something but I don't know what ?? 

Help please.

**My podfile:**

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'pop', '~> 1.0'
pod 'fluid-slider'

  # Pods for Example

end
```

By the way I also tried running w source files.

**Comment by ober01** [comment]
#12

**Comment by BedirT** [comment]
Why would I import fluid_slider ? It is already in the workspace as Slider ?

**Comment by ober01** [comment]
I created a test project and it is works 
![test-fluidslider](https://user-images.githubusercontent.com/5435782/38351774-aaef4562-38b9-11e8-8f66-8a0a0a38cfb6.gif)

**Comment by BedirT** [comment]
OK, it worked when I created a new project. But I still couldn't pass the issue for the example project. Anyway just letting you know. There is another problem now, but ill make new issue I guess.
