### ISSUE TITLE
Minimum and Maximum Value for Slider Fraction

### ISSUE THREAD

**Issue by ankita94p** [Ramotion/fluid-slider#17]
How can i change the slider minimum value default 0 to another?
I am changing the minimum and maximum label attributed text but I am unable to change the default minimum fraction value that starts from 0 and the maximum value of fraction

![img_0662](https://user-images.githubusercontent.com/40234586/41406136-42c3864e-6fe9-11e8-931d-79eae43055af.jpg)

**Comment by sonnetm** [comment]
@ankita94p  Have you solved this?

**Comment by ankita94p** [comment]
@sonnetm yeah, with the help of some mathematic calculation.

**Comment by iAmita** [comment]
@sonnetm Can you please explain what calculation you have done? Thanks in advance.

**Comment by ankita94p** [comment]
Hey @sonnetm 
Here is the calculation, the calculated code which solved this issue.

sliderView.attributedTextForFraction = { fraction in
            let formatter = NumberFormatter()
            formatter.maximumFractionDigits = 0
            **let string = formatter.string(from: (2 + (8 * fraction)) as NSNumber) ?? ""**
            return NSAttributedString(string: ("$" + string),
                                      attributes: [NSAttributedStringKey.foregroundColor: UIColor.black])
}
sliderView.setMinimumLabelAttributedText(NSAttributedString(string: "$2",
                                                                         attributes: [NSAttributedStringKey.foregroundColor: UIColor.white]))
sliderView.setMaximumLabelAttributedText(NSAttributedString(string: "$10",
                                                                         attributes: [NSAttributedStringKey.foregroundColor: UIColor.white]))
