### ISSUE TITLE
Just a big confused on how to get the current Value from a UIControl

### ISSUE THREAD

**Issue by RushanB** [Ramotion/fluid-slider#18]
I'm sure there is an easy way to get the value such as Slider.currentValue? or is Slider.fraction the same thing as currentValue.

**Comment by HadiYaac** [comment]
Hi @RushanB , please can you help me since I had the same confusion 🤒

**Comment by RushanB** [comment]
Hi @HadiYaac, I cant remember off the top of my head but I believe it was something like slider.fraction

**Comment by HadiYaac** [comment]
> Hi @HadiYaac, I cant remember off the top of my head but I believe it was something like slider.fraction

Thanks for your reply 👍
