### ISSUE TITLE
Bubble not connected

### ISSUE THREAD

**Issue by mightymango** [Ramotion/fluid-slider#20]
I am experiencing a problem where the bubble is not connected to the bar as is shown in your animated gif.

![fluid](https://user-images.githubusercontent.com/1525576/45144963-6ebfdf80-b1b7-11e8-9ec0-f172bc2acbad.png)

I am using code from your example project.

**Comment by chebur** [comment]
The effect is enabled when you run on device only.
It is because the simulator uses CPU to render the effect which leads to dropped frames.
See `isAnimationAllowed` method
