### ISSUE TITLE
Pop is not connecting with slider i mean in beet attachment is not coming 

### ISSUE THREAD

**Issue by chikithreddy** [Ramotion/fluid-slider#29]
<img width="1440" alt="screenshot 2019-02-27 at 5 15 59 pm" src="https://user-images.githubusercontent.com/46279752/53488117-65069d00-3ab3-11e9-9077-540ede868843.png">

**Comment by Juriv** [comment]
@chikithreddy please try it on the real device, iOS Simulator doesn't support it.

**Comment by chikithreddy** [comment]
Hello juri,


It is working fine. Thanks for the reply

Regards,
chikithreddy
