### ISSUE TITLE
Done like design

### ISSUE THREAD

**Issue by anmassdevs** [Ramotion/fluid-slider#37]
After install and configuration, I got a result not the same with design 
![Untitled-1](https://user-images.githubusercontent.com/53417111/62755081-c25c3c80-ba9c-11e9-95c3-d627e15ce5d0.gif)
What attributes to make solid between a circle and rectangle?

**Comment by Juriv** [comment]
@anmassdevs iOS simulator doesn't render it properly, check on real device and it will be connected

**Comment by anmassdevs** [comment]
Thanks Juriv.
