### ISSUE TITLE
Cannot import pop

### ISSUE THREAD

**Issue by uargh** [Ramotion/fluid-slider#4]
Hi,
when trying to include the component into a project via Carthage i get the following error:
`[…]/Carthage/Checkouts/fluid-slider/Sources/ValueView.swift:10:8: error: no such module 'pop'
import pop`

**Comment by Juriv** [comment]
@uargh it should work now, could you please check

**Comment by HamzaGhazouani** [comment]
Hi @uargh, did you try to install it using: `Carthage update --cache-builds --platform ios`

**Comment by ikolpachkov** [comment]
Please run `carthage bootstrap --platform iOS` before compile Xcode project
