### ISSUE TITLE
Animation doesn't work on simulator

### ISSUE THREAD

**Issue by oguzveozturk** [Ramotion/fluid-slider#45]
![fluid_slider](https://user-images.githubusercontent.com/54209230/75152803-f2a6b800-571a-11ea-8451-64ee51cd3341.png)
why is this animation doesn't work on simulator? any idea?

device ios 12 and ios 13 tested. working.
simulator only ios 13 tested. not working.

**Comment by Juriv** [comment]
The effect is enabled when you run on device only.
It is because the simulator uses CPU to render the effect which leads to dropped frames.
See isAnimationAllowed method

**Comment by oguzveozturk** [comment]
ok then. thanks 👍🏼
