### ISSUE TITLE
[!] Unable to find a specification for `fluid-slider`

### ISSUE THREAD

**Issue by aditya5045** [Ramotion/fluid-slider#6]
Installing `pod 'fluid-slider'` but its showing  

`[!] Unable to find a specification for `fluid-slider``

plz help

**Comment by ober01** [comment]
I created test project with the cocoapods, it works fine 
![image](https://user-images.githubusercontent.com/5435782/34093109-905a5f70-e3d7-11e7-9a5f-983cdf2f90ea.png)

Maybe you have problem with your the cocoapods

**Comment by ikolpachkov** [comment]
@aditya5045 You can try: 
```
pod repo remove master
pod setup
pod install
```
